# 1. The Application Port
server:
  port: 8081

spring:
  application:
    name: consumer

  # 2. The Conveyor Belt (Kafka)
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: reconciliation-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        # Ignore the Producer's shipping label
        spring.json.use.type.headers: false
        # Force the JSON into the Consumer's local blueprint
        spring.json.value.default.type: com.maang.reconciliation.consumer.model.Transaction

  # 3. The Temporary Cache (Redis)
  data:
    redis:
      host: localhost
      port: 6379

  # 4. The Permanent Vault (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_reconciliation
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  # 5. The Magic Table Builder (Hibernate)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true